# Generated by Django 2.2.6 on 2019-10-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20191007_1642'),
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='platform',
            field=models.ManyToManyField(to='games.Platform'),
        ),
    ]
