# Generated by Django 2.2.6 on 2019-10-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191004_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
