# Generated by Django 2.2.6 on 2019-10-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20191007_1642'),
        ('accounts', '0006_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(to='games.Games'),
        ),
    ]
