# Generated by Django 2.2.6 on 2019-10-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Action', 'Action')], max_length=150)),
                ('platform', models.CharField(choices=[('Playstation 4', 'Playstation 4 ')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('developer', models.CharField(choices=[('Blizzard', 'Blizzard')], max_length=150)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('genre', models.ManyToManyField(to='games.Genre')),
            ],
        ),
    ]
