# Generated by Django 2.2.6 on 2019-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191006_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='developer',
            field=models.CharField(choices=[('Blizzard', 'Blizzard'), ('SONY', 'SONY'), ('EA', 'EA')], max_length=150),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('RPG', 'RPG'), ('Multiplayer', 'Multiplayer')], max_length=150),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform',
            field=models.CharField(choices=[('Playstation 4', 'Playstation 4'), ('PC', 'PC'), ('XBOX-ONE', 'XBOX-ONE'), ('Nintendo', 'Nintendo')], max_length=150),
        ),
    ]
