# Generated by Django 2.2.6 on 2019-10-09 12:45

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('accounts', '0007_auto_20191007_1642'),
        ('guilds', '0002_guild_platform'),
        ('games', '0004_auto_20191007_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
